INSERT INTO `SYS_USER` VALUES (1, 'admin', '123456');
INSERT INTO `SYS_USER` VALUES (2, 'normal', '123456');


INSERT INTO `SYS_ROLE` VALUES (1, 'ROLE_ADMIN');
INSERT INTO `SYS_ROLE` VALUES (2, 'ROLE_NORMAL');

INSERT INTO `SYS_USER_ROLE` VALUES (1, 1);
INSERT INTO `SYS_USER_ROLE` VALUES (2, 2);


INSERT INTO `SYS_AUTHORITY` VALUES (1, '/test/a');
INSERT INTO `SYS_AUTHORITY` VALUES (2, '/test/b');

INSERT INTO `SYS_USER_AUTHORITY` VALUES (1, 1);
INSERT INTO `SYS_USER_AUTHORITY` VALUES (1, 2);
INSERT INTO `SYS_USER_AUTHORITY` VALUES (2, 2);

