-- noinspection SqlNoDataSourceInspectionForFile

-- h2数据库大小写不敏感，官网地址：http://www.h2database.com/html/main.html
-- 用户信息表
CREATE TABLE IF NOT EXISTS SYS_USER
(
    ID            IDENTITY        PRIMARY KEY NOT NULL,
    USERNAME      VARCHAR(64)     NOT NULL,
    PASSWORD      VARCHAR(64)     NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS USER_INDEX_USERNAME ON SYS_USER (USERNAME);

-- 角色信息表
CREATE TABLE IF NOT EXISTS SYS_ROLE
(
    ID            IDENTITY        PRIMARY KEY NOT NULL,
    NAME          VARCHAR(64)     NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ROLE_INDEX_NAME ON SYS_ROLE (NAME);

-- 用户角色表
CREATE TABLE IF NOT EXISTS SYS_USER_ROLE
(
    USER_ID       BIGINT          NOT NULL,
    ROLE_ID       BIGINT          NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS USER_ROLE_INDEX_ID ON SYS_USER_ROLE (USER_ID, ROLE_ID);

-- 权限信息表
CREATE TABLE IF NOT EXISTS SYS_AUTHORITY
(
    ID            IDENTITY        PRIMARY KEY NOT NULL,
    NAME          VARCHAR(64)     NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS AUTHORITY_INDEX_NAME ON SYS_AUTHORITY (NAME);

-- 用户权限表
CREATE TABLE IF NOT EXISTS SYS_USER_AUTHORITY
(
    USER_ID       BIGINT          NOT NULL,
    AUTHORITY_ID  BIGINT          NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS USER_AUTHORITY_INDEX_ID ON SYS_USER_AUTHORITY (USER_ID, AUTHORITY_ID);

-- 保函流水
CREATE TABLE IF NOT EXISTS TRANSACT_HISTORY (
    PROJECT_NAME VARCHAR(32) ,
    PROJECT_CODE VARCHAR(32) ,
    KB_TIME VARCHAR(32) ,
    TRANSACT_TIME VARCHAR(32) ,
    TB_UNIT_NAME VARCHAR(32) ,
    ZB_UNIT_NAME VARCHAR(32) ,
    BAOHAN_MONEY VARCHAR(32) ,
    INVOICE_MONEY VARCHAR(32) ,
    APPLICATION_NO VARCHAR(32) ,
    BAOHAN_CODE VARCHAR(32) ,
    REGION_CODE VARCHAR(32) ,
    REGION_NAME VARCHAR(32) ,
    PRODUCT_NAME VARCHAR(32) ,
    ORG_NAME VARCHAR(32)
);
CREATE UNIQUE INDEX IF NOT EXISTS TRANSACT_HISTORY_UNIT_NAME ON TRANSACT_HISTORY (PROJECT_CODE, TB_UNIT_NAME, TRANSACT_TIME);
